### ISSUE TITLE
How to set the type of an attribute?

### ISSUE THREAD

**Issue by ialazzon** [pyecore/pyuml2#3]
I hope to get a help on this issue. 
import pyuml2.uml as uml 
a_instance = uml.Property()
a_instance.name = "firstName"
Here I want to set the type of the attribute age as String. How to do this?
Note that *a_instance.datatype = uml.uml.String*, for example, results in the following exception:
pyecore.valuecontainer.BadValueError: Expected type <class 'pyuml2.uml.uml.DataType'>, but got type EDataType with value String(str) instead for feature <EReference datatype: <class 'pyuml2.uml.uml.DataType'>> of <EClass name="Property">

**Comment by aranega** [comment]
Hi @ialazzon ,

Thanks for posting about your issue! As you saw, the way of dealing with primitive types in UML is far from obvious. The thing is that some primitive types are defined as part of a library in an external file. There is basically two ways of setting a primitive type for a `Property`.

1. you load the primitive type library file where they are modeled and you access them,
2. you recreate them in your model somewhere as `PrimitiveType`.

Honestly, the two ways are more or less equivalent at the end, depending a lot of what you'll do with your model next (code generation in Python, or in Eclipse, loading it with other tools that are compatible, but that are waiting for types in a special way...etc).

## 1st solution 

Loading the library file requires to load and register first many metamodels as the library files uses/defines a lot of elements that are used for dealing with UML profiles.
You can find the library in the `profiles/` directory if you switch to one of the branch `profile-codegen` or `profiles`.

Then, here is the snippet to register the needed metamodels, load the library and extract the `PrimitiveType`:

```python
from pyecore.resources import ResourceSet
import pyuml2.types as types
import pyuml2.uml as uml2
import pyuml2.standard as standard
import pyecore.ecore as ecore

rset = ResourceSet()
rset.metamodel_registry[uml2.nsURI] = uml2
rset.metamodel_registry['http://www.eclipse.org/uml2/schemas/Ecore/5'] = ecore
rset.metamodel_registry[types.nsURI] = types
rset.metamodel_registry[standard.nsURI] = standard

# we load the model
primitive_types = rset.get_resource('UMLPrimitiveTypes.library.uml').contents[0]

# we extract all the primitive types
Boolean, Integer, Real, String, UnlimitedNatural = primitive_types.packagedElement

# here we create a property and we link it to the loaded type
p = uml2.Property(name='foo', type=String)

print(p.type.name)
```

## 2nd solution 

In this solution, you create the `PrimitiveType` by hand and you reuse it any time you need it. 
If you choose this solution, don't forget to add the created `PrimitiveType` to your model (like added in a `Package` or `Model` somewhere) otherwise, the `PrimitiveType` will not be serialized if you save your model as XMI or JSON.

```python
import pyuml2.uml as uml2

String = uml2.PrimitiveType(name='String')
p = uml2.Property(name='foo', type=String)

print(p.type.name)
```


I hope this helps! UML is really not pratical when you want to conform to the standard and you need to reuse existing primitive types.

**Comment by ialazzon** [comment]
Thank you very much. Your answer has solved my problems.
